[package]
name = "lidrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
property = "0.3.*"
regex = "1.5.*"
num_enum = "0.5.*"
